Update github-actions-var-test.yml

diff --git a/.github/workflows/github-actions-var-test.yml b/.github/workflows/github-actions-var-test.yml
--- a/.github/workflows/github-actions-var-test.yml
+++ b/.github/workflows/github-actions-var-test.yml
@@ -1,3 +1,5 @@
+name: GitHub Actions Variable Test
+
 on:
   workflow_dispatch:
 env:
@@ -5,26 +7,18 @@ env:
   env_var: ${{ vars.ENV_CONTEXT_VAR }}
 
 jobs:
-  display-variables:
-    name: ${{ vars.JOB_NAME }}
-    # You can use configuration variables with the `vars` context for dynamic jobs
-    if: ${{ vars.USE_VARIABLES == 'true' }}
-    runs-on: ${{ vars.RUNNER }}
-    environment: ${{ vars.ENVIRONMENT_STAGE }}
+  test-variable:
+    runs-on: ubuntu-latest
     steps:
-    - name: Use variables
-      run: |
-        echo "repository variable : $REPOSITORY_VAR"
-        echo "organization variable : $ORGANIZATION_VAR"
-        echo "overridden variable : $OVERRIDE_VAR"
-        echo "variable from shell environment : $env_var"
-      env:
-        REPOSITORY_VAR: ${{ vars.REPOSITORY_VAR }}
-        ORGANIZATION_VAR: ${{ vars.ORGANIZATION_VAR }}
-        OVERRIDE_VAR: ${{ vars.OVERRIDE_VAR }}
-        
-    - name: ${{ vars.HELLO_WORLD_STEP }}
-      if: ${{ vars.HELLO_WORLD_ENABLED == 'true' }}
-      uses: actions/hello-world-javascript-action@main
-      with:
-        who-to-greet: ${{ vars.GREET_NAME }}
+      - name: Print Repository Variable
+        run: |
+          echo "The value of JOB_NAME is: ${{ vars.JOB_NAME }}"
+
+      - name: Example Usage of JOB_NAME
+        run: |
+          if [[ "${{ vars.JOB_NAME }}" == "var-test" ]]; then
+            echo "JOB_NAME matches 'var-test'. Test passed!"
+          else
+            echo "JOB_NAME does not match 'var-test'. Test failed."
+            exit 1
+          fi
